services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile.postgres
    container_name: rest_postgres
    ports:
      - "5438:5438" # change port to 5438 to avoid conflict with other postgres instances
    environment:
      - PGDATA=/var/lib/postgresql/pgdata
      
    command: ["postgres", "-c", "port=5438"]
    volumes:
      - postgres_data:/var/lib/postgresql/pgdata
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - shared_network


  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: resturant_api
    ports:
      - "8500:8500"
    depends_on:
      - postgres
    restart: always

    volumes:
      - ./:/usr/src/resturant_api
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8500 --reload
    networks:
      - shared_network

  redis:
    container_name: resturant_redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - shared_network

  frontend:
    build:
      context: ./frontend/Frontend
      dockerfile: Dockerfile.frontend
    container_name: restaurant_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always
    networks:
      - shared_network

volumes:
  postgres_data:

networks:
  shared_network:
    external: true