"""Add image_url to menu_item

Revision ID: 21dfc5c936a5
Revises: a6a4f6c2a195
Create Date: 2025-06-11 21:35:08.149434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21dfc5c936a5'
down_revision: Union[str, None] = 'a6a4f6c2a195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'image_url')
    # ### end Alembic commands ###
