"""cahnge directoies and id  

Revision ID: 9f8a4f6fa5ed
Revises: bbad1f00f820
Create Date: 2025-05-26 21:00:29.345259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8a4f6fa5ed'
down_revision: Union[str, None] = 'bbad1f00f820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'table_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('menu_category', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_menu_category_id', table_name='menu_category')
    op.create_unique_constraint(None, 'menu_category', ['id'])
    op.alter_column('menu_item', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('menu_item', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_menu_item_id', table_name='menu_item')
    op.create_unique_constraint(None, 'menu_item', ['id'])
    op.alter_column('order', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order', 'waiter_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order', 'kitchen_staff_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order', 'table_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order', 'special_request',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_order_id', table_name='order')
    op.create_unique_constraint(None, 'order', ['id'])
    op.drop_index('ix_order_item_id', table_name='order_item')
    op.create_unique_constraint(None, 'order_item', ['id'])
    op.drop_index('ix_restaurant_table_id', table_name='restaurant_table')
    op.create_unique_constraint(None, 'restaurant_table', ['id'])
    op.drop_index('ix_user_id', table_name='user')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_constraint(None, 'restaurant_table', type_='unique')
    op.create_index('ix_restaurant_table_id', 'restaurant_table', ['id'], unique=False)
    op.drop_constraint(None, 'order_item', type_='unique')
    op.create_index('ix_order_item_id', 'order_item', ['id'], unique=False)
    op.drop_constraint(None, 'order', type_='unique')
    op.create_index('ix_order_id', 'order', ['id'], unique=False)
    op.alter_column('order', 'special_request',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('order', 'table_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('order', 'kitchen_staff_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('order', 'waiter_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('order', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'menu_item', type_='unique')
    op.create_index('ix_menu_item_id', 'menu_item', ['id'], unique=False)
    op.alter_column('menu_item', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('menu_item', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'menu_category', type_='unique')
    op.create_index('ix_menu_category_id', 'menu_category', ['id'], unique=False)
    op.alter_column('menu_category', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customer', 'table_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
