"""remove id  

Revision ID: ce62d40cc2bc
Revises: 9f8a4f6fa5ed
Create Date: 2025-05-26 21:05:15.820646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce62d40cc2bc'
down_revision: Union[str, None] = '9f8a4f6fa5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_category_id_key', 'menu_category', type_='unique')
    op.create_index(op.f('ix_menu_category_id'), 'menu_category', ['id'], unique=False)
    op.drop_constraint('menu_item_id_key', 'menu_item', type_='unique')
    op.create_index(op.f('ix_menu_item_id'), 'menu_item', ['id'], unique=False)
    op.drop_constraint('order_id_key', 'order', type_='unique')
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.drop_constraint('order_item_id_key', 'order_item', type_='unique')
    op.create_index(op.f('ix_order_item_id'), 'order_item', ['id'], unique=False)
    op.drop_constraint('restaurant_table_id_key', 'restaurant_table', type_='unique')
    op.create_index(op.f('ix_restaurant_table_id'), 'restaurant_table', ['id'], unique=False)
    op.drop_constraint('user_id_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_unique_constraint('user_id_key', 'user', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_restaurant_table_id'), table_name='restaurant_table')
    op.create_unique_constraint('restaurant_table_id_key', 'restaurant_table', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_order_item_id'), table_name='order_item')
    op.create_unique_constraint('order_item_id_key', 'order_item', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.create_unique_constraint('order_id_key', 'order', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_menu_item_id'), table_name='menu_item')
    op.create_unique_constraint('menu_item_id_key', 'menu_item', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_menu_category_id'), table_name='menu_category')
    op.create_unique_constraint('menu_category_id_key', 'menu_category', ['id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
